add edit button
francoax/dsw-app pull request #47
Opened 2023-11-30 03:26 UTC by octapereyra

2023-12-03 19:32 UTC, francoax requested changes

2023-12-03 19:32 UTC, francoax commented on src/app/modules/user/update-data/update-data.component.ts
> +          alert(err.message);
Cambia el alert por el toast

2023-12-04 22:35 UTC, octapereyra commented
ready to merge

2023-12-05 20:30 UTC, francoax approved these changes

2023-12-05 20:31 UTC, merged