Feature/cars modifications
francoax/dsw-app pull request #59
Opened 2023-12-05 21:28 UTC by NicolasDiDio09

2023-12-05 22:50 UTC, octapereyra requested changes
cambiar mensaje del modal

2023-12-05 22:51 UTC, octapereyra requested changes

2023-12-05 22:51 UTC, octapereyra commented on src/app/modules/admin/cars-list/cars-list.component.html
> +  <ng-container modal-message>Estas seguro de eliminar esta Propiedad?</ng-container>
cambiar mensaje

2023-12-07 15:33 UTC, NicolasDiDio09 commented on src/app/modules/admin/cars-list/cars-list.component.html
> +  <ng-container modal-message>Estas seguro de eliminar esta Propiedad?</ng-container>
ready

2023-12-07 15:41 UTC, octapereyra approved these changes

2023-12-12 21:39 UTC, merged